version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-crm
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: crm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crmdb
      SPRING_DATASOURCE_USERNAME: crmuser
      SPRING_DATASOURCE_PASSWORD: crmpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  postgres_data:
